
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.
# Application Template: projects/google-mpf-5txkh4agy9c2/locations/us-central1/spaces/default-space/applicationTemplates/template-three-one

output "cloud-run-1_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.cloud-run-1.service_uri
}
