
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.
# Application Template: projects/google-mpf-5txkh4agy9c2/locations/us-central1/spaces/default-space/applicationTemplates/template-three-one

cloud-run-1_containers = [{
  container_image = "us-docker.pkg.dev/cloudrun/container/hello"
  container_name  = "service-container"
  ports = {
    container_port = 8080
  }
}]
